name: mastodon
description: A robust Dart API for the Mastodon network.
version: 0.1.0
author: Luke Pighetti <lukepighetti@gmail.com>
homepage: https://github.com/lukepighetti/mastodon-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+1
  json_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^1.2.5
  json_serializable: ^2.0.2
  test: ^1.0.0
