name: mastodon
description: A robust Dart API for the Mastodon network.
version: 1.0.0
author: Luke Pighetti <lukepighetti@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_serializable: ^2.0.2

dev_dependencies:
  build_runner: ^1.2.5
  test: ^1.0.0
