name: mastodon_dart
description: The official Dart library for accessing the Mastodon API. Use in conjunction with mastodon_flutter to build a Flutter Mastodon app.
version: 0.3.2
homepage: https://github.com/lukepighetti/mastodon_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5
  json_annotation: ^4.7.0
  rxdart: ^0.27.5
  web_socket_channel: ^2.2.0
  async: ^2.10.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  stack_trace: ^1.10.0
  test: ^1.22.0
